[project]
name = "pyvegas-mtg-django"
version = "0.1.0"
description = "Magic the Gathering Django ORM demo"
requires-python = ">=3.8"
dependencies = [
    "asgiref==3.5.2",
    "Django==4.0.5",
    "django-extensions==3.1.5",
    "sqlparse==0.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
# uv-specific configurations can go here