# Generated by Django 4.0.5 on 2022-07-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('U', 'Blue'), ('W', 'White'), ('B', 'Black')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('flavor', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=5)),
                ('toughness', models.CharField(max_length=5)),
                ('rarity', models.CharField(max_length=20)),
                ('set_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=300)),
                ('colors', models.ManyToManyField(to='cards.color')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.edition')),
            ],
        ),
    ]
