# Generated by Django 4.0.5 on 2025-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
